import { Hero } from './hero';


export const HEROES : Hero[] = [
  { id: 1, name : 'Canada' },
  { id: 2, name : 'Mexico' },
  { id: 3, name : 'Guatemala' },
  { id: 4, name : 'El Salvador' },
  { id: 5, name : 'Honduras' },
  { id: 6, name : 'Nicaragua' },
  { id: 7, name : 'Costa Rica' },
  { id: 8, name : 'Panama' },
  { id: 9, name : 'Colombia' },
  { id: 10, name : 'Venezuela' },
  { id: 11, name : 'Surinam' },
  { id: 12, name : 'Guyana' },
  { id: 13, name : 'Brazil' },
  { id: 14, name : 'Ecuador' },
  { id: 15, name : 'Peru' },
  { id: 16, name : 'Bolivia' },
  { id: 17, name : 'Chile' },
  { id: 18, name : 'Argentina' },
  { id: 19, name : 'Paraguay' },
  { id: 20, name : 'Uruguay' },
  { id: 21, name : 'Bahamas' },
  { id: 22, name : 'Turks and Caicos Islands' },
  { id: 23, name : 'Cuba' },
  { id: 24, name : 'Haiti' },
  { id: 25, name : 'Dominican Republic' },
  { id: 26, name : 'Jamaica' },
  { id: 27, name : 'Puerto Rico' },
  { id: 28, name : 'Aruba' },
  { id: 29, name : 'Bonaire' },
  { id: 30, name: 'Curacao' },
  { id: 31, name : 'Angilla' },
  { id: 32, name : 'Antigua and Barbuda' },
  { id: 33, name : 'British Virgin Islands' },
  { id: 34, name : 'Guadeloupe' },
  { id: 35, name : 'Barbados' },
  { id: 36, name : 'Trinidad and Tobago' },
]
// export const HEROES: Hero[] = [
//   { id: 11, name: 'Dr Nice' },
//   { id: 12, name: 'Narco' },
//   { id: 13, name: 'Bombasto' },
//   { id: 14, name: 'Celeritas' },
//   { id: 15, name: 'Magneta' },
//   { id: 16, name: 'RubberMan' },
//   { id: 17, name: 'Dynama' },
//   { id: 18, name: 'Dr IQ' },
//   { id: 19, name: 'Magma' },
//   { id: 20, name: 'Tornado' }
// ];
